USE PLANESDB;

ANALYZE TABLE PERSON;
ANALYZE TABLE CORPORATION;
ANALYZE TABLE OWNER_TABLE;
ANALYZE TABLE HANGAR;
ANALYZE TABLE PLANE_TYPE;
ANALYZE TABLE AIRPLANE;
ANALYZE TABLE EMPLOYEE;
ANALYZE TABLE PILOT;
ANALYZE TABLE SERVICE;
ANALYZE TABLE OWNS;
ANALYZE TABLE FLIES;
ANALYZE TABLE MAINTAIN;
ANALYZE TABLE WORKS_ON;

SELECT CONCAT('SELECT ''', table_name, ''' AS table_name, COUNT(*) AS row_count FROM ', table_name, ';')
FROM information_schema.tables
WHERE table_schema = 'PLANESDB' AND table_type = 'BASE TABLE';

SELECT 'airplane' AS table_name, COUNT(*) AS row_count FROM airplane;
SELECT 'corporation' AS table_name, COUNT(*) AS row_count FROM corporation;
SELECT 'employee' AS table_name, COUNT(*) AS row_count FROM employee;
SELECT 'flies' AS table_name, COUNT(*) AS row_count FROM flies;
SELECT 'hangar' AS table_name, COUNT(*) AS row_count FROM hangar;
SELECT 'maintain' AS table_name, COUNT(*) AS row_count FROM maintain;
SELECT 'owner_table' AS table_name, COUNT(*) AS row_count FROM owner_table;
SELECT 'owns' AS table_name, COUNT(*) AS row_count FROM owns;
SELECT 'person' AS table_name, COUNT(*) AS row_count FROM person;
SELECT 'pilot' AS table_name, COUNT(*) AS row_count FROM pilot;
SELECT 'plane_type' AS table_name, COUNT(*) AS row_count FROM plane_type;
SELECT 'service' AS table_name, COUNT(*) AS row_count FROM service;
SELECT 'works_on' AS table_name, COUNT(*) AS row_count FROM works_on;


SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'PLANESDB' ORDER BY CREATE_TIME ASC;
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'PLANESDB' ORDER BY TABLE_NAME, COLUMN_NAME ASC;
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'PLANESDB' ORDER BY TABLE_NAME ASC;

SHOW TABLES;

SELECT * FROM PERSON;
SELECT * FROM CORPORATION;
SELECT * FROM OWNER_TABLE;
SELECT * FROM HANGAR;
SELECT * FROM PLANE_TYPE;
SELECT * FROM AIRPLANE;
SELECT * FROM EMPLOYEE;
SELECT * FROM PILOT;
SELECT * FROM SERVICE;
SELECT * FROM OWNS;
SELECT * FROM FLIES;
SELECT * FROM MAINTAIN;
SELECT * FROM WORKS_ON;
