CREATE DATABASE IF NOT EXISTS INPUT_VALID_TEST;
USE INPUT_VALID_TEST;

DROP USER IF EXISTS 'INPUT_TEST'@'localhost';
CREATE USER 'INPUT_TEST'@'localhost' IDENTIFIED BY 'inputvalid';
GRANT ALL ON INPUT_VALID_TEST.* TO 'INPUT_TEST'@'localhost';
FLUSH PRIVILEGES;
COMMIT;

CREATE TABLE IF NOT EXISTS users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);





SELECT * FROM users;